#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR
virtualenv pyenv
echo '*' > pyenv/.gitignore
. pyenv/bin/activate
pip install -r requirements.txt
